### ISSUE TITLE
Fill out all tech used in Tech Stack of Readme

### ISSUE THREAD

**Issue by MattRudy** [rosekamallove/youtemy#77]
Someone with better knowledge of the tech used in the project should complete the 'Tech Stack' section of the Readme file.

* Add icons for all tech used in the project
* Add links for all tech used in the project
* Add a description of the front-end and back-end approaches

**Comment by rosekamallove** [comment]
I don't really know how to add the icons, if you can tell me I'll push that.

**Comment by MattRudy** [comment]
Sure - this is what the 'Tech Stack' section of the README looks like now:

```
<!-- Tech Stack Block -->
# 🚀 Tech Stack
<p align="center">
    <a href="https://firebase.google.com"><img width=32 height=32 src="https://firebase.google.com/downloads/brand-guidelines/SVG/logo-logomark.svg" alt="Firebase logo"></a>
</p>

YouTemy is a web app built with the following:
* [Javascript](https://www.javascript.com)
* [ReactJS](https://reactjs.org/)
* [Firebase](https://firebase.google.com)
* [YouTube Data API V3](https://developers.google.com/youtube/v3)
```

To add more icons:
1. Find a link on the source website to the SVG icon, such as https://firebase.google.com/downloads/brand-guidelines/SVG/logo-logomark.svg
2. If you can't find a link, save a copy of the SVG logo in this repository and use that instead
3. Add another image section to the HTML block. For example, three images would like look this:

```
<p align="center">
    <a href="https://firebase.google.com"><img width=32 height=32 src="https://firebase.google.com/downloads/brand-guidelines/SVG/logo-logomark.svg" alt="Firebase logo"></a>
    **<a href="https://firebase.google.com"><img width=32 height=32 src="https://firebase.google.com/downloads/brand-guidelines/SVG/logo-logomark.svg" alt="Firebase logo"></a>
    <a href="https://firebase.google.com"><img width=32 height=32 src="https://firebase.google.com/downloads/brand-guidelines/SVG/logo-logomark.svg" alt="Firebase logo"></a>**
</p>
```

**Comment by MattRudy** [comment]
Other than that, I'd recommend changing the bullet list of technology links into two paragraphs - one describing front end (with links) and one describing backend (with links). This will help developers understand your approach faster so they can help support the project!

**Comment by rosekamallove** [comment]
Okay, Thanks again!!
