### ISSUE TITLE
Navbar scrolls along with the video player

### ISSUE THREAD

**Issue by Ritesh055** [rosekamallove/youtemy#8]
On scrolling below the navbar scrolls above with the video player but the playlist sticks there.

**Before Scroll**
![Issue 1](https://user-images.githubusercontent.com/54197176/128322929-1794f197-5e32-47e6-bd52-11909b3cb814.png)

**After Scroll**
![Issue 2](https://user-images.githubusercontent.com/54197176/128322915-fdd65978-e7b5-4331-9bf0-78131d1632eb.png)

**Comment by rosekamallove** [comment]
fixed !
